# Ensure the DB Password is changed before deployment
# Also recommended it goes behind a reverse-proxy like nginx or caddy
# so https can be used
version: "3"
services:
  competition-manager:
    image: ghcr.io/lambarchie/competition-manager:latest
    container_name: competition-manager
    ports:
      - 80:5000
    env_file:
      - .env
    environment:
      # Change the password
      - DATABASE_URL=postgresql+psycopg2://docker:change-me!@postgres/competitionmanager
    volumes:
      - competition-manager-logs:/app/logs
      - competition-manager-uploads:/app/uploads
    links:
      - postgres:postgres
    restart: unless-stopped
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=docker
      # Change the password
      - POSTGRES_PASSWORD=change-me!
      - POSTGRES_DB=competitionmanager
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  competition-manager-logs:
  competition-manager-uploads:
  postgres-data:
