"""add uploads table

Revision ID: 38fe892c534f
Revises: 0bf9e306bc2c
Create Date: 2019-09-08 13:50:25.453424

"""
from alembic import op
import sqlalchemy as sa
#manually added below
from app.database.uuid import GUID
sa.GUID = GUID

# revision identifiers, used by Alembic.
revision = '38fe892c534f'
down_revision = '0bf9e306bc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_uploads',
    sa.Column('uuid', sa.GUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_uploads')
    # ### end Alembic commands ###
