"""added user tokens

Revision ID: 687606e2d118
Revises: d0dddf4e1864
Create Date: 2019-03-29 15:26:43.792570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687606e2d118'
down_revision = 'd0dddf4e1864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
