"""updated review core

Revision ID: b3784069db40
Revises: 687606e2d118
Create Date: 2019-04-17 19:56:12.826540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3784069db40'
down_revision = '687606e2d118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['compId'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('review', sa.Column('catId', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('compId', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'review', 'competition', ['compId'], ['id'])
    op.create_foreign_key(None, 'review', 'category', ['catId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'name')
    op.drop_column('review', 'compId')
    op.drop_column('review', 'catId')
    op.drop_table('category')
    op.drop_table('competition')
    # ### end Alembic commands ###
